/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AffiliateDisclosureRouteImport } from './routes/affiliate-disclosure'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FlatRoofCostRouteImport } from './routes/flat-roof-cost'
import { Route as NewRoofCostRouteImport } from './routes/new-roof-cost'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RoofCostCalculatorRouteImport } from './routes/roof-cost-calculator'
import { Route as RoofRepairCostRouteImport } from './routes/roof-repair-cost'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDisclosureRoute = AffiliateDisclosureRouteImport.update({
  id: '/affiliate-disclosure',
  path: '/affiliate-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FlatRoofCostRoute = FlatRoofCostRouteImport.update({
  id: '/flat-roof-cost',
  path: '/flat-roof-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoofCostRoute = NewRoofCostRouteImport.update({
  id: '/new-roof-cost',
  path: '/new-roof-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RoofCostCalculatorRoute = RoofCostCalculatorRouteImport.update({
  id: '/roof-cost-calculator',
  path: '/roof-cost-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const RoofRepairCostRoute = RoofRepairCostRouteImport.update({
  id: '/roof-repair-cost',
  path: '/roof-repair-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/contact': typeof ContactRoute
  '/flat-roof-cost': typeof FlatRoofCostRoute
  '/new-roof-cost': typeof NewRoofCostRoute
  '/privacy': typeof PrivacyRoute
  '/roof-cost-calculator': typeof RoofCostCalculatorRoute
  '/roof-repair-cost': typeof RoofRepairCostRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/contact': typeof ContactRoute
  '/flat-roof-cost': typeof FlatRoofCostRoute
  '/new-roof-cost': typeof NewRoofCostRoute
  '/privacy': typeof PrivacyRoute
  '/roof-cost-calculator': typeof RoofCostCalculatorRoute
  '/roof-repair-cost': typeof RoofRepairCostRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/contact': typeof ContactRoute
  '/flat-roof-cost': typeof FlatRoofCostRoute
  '/new-roof-cost': typeof NewRoofCostRoute
  '/privacy': typeof PrivacyRoute
  '/roof-cost-calculator': typeof RoofCostCalculatorRoute
  '/roof-repair-cost': typeof RoofRepairCostRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/contact'
    | '/flat-roof-cost'
    | '/new-roof-cost'
    | '/privacy'
    | '/roof-cost-calculator'
    | '/roof-repair-cost'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/contact'
    | '/flat-roof-cost'
    | '/new-roof-cost'
    | '/privacy'
    | '/roof-cost-calculator'
    | '/roof-repair-cost'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/contact'
    | '/flat-roof-cost'
    | '/new-roof-cost'
    | '/privacy'
    | '/roof-cost-calculator'
    | '/roof-repair-cost'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AffiliateDisclosureRoute: typeof AffiliateDisclosureRoute
  ContactRoute: typeof ContactRoute
  FlatRoofCostRoute: typeof FlatRoofCostRoute
  NewRoofCostRoute: typeof NewRoofCostRoute
  PrivacyRoute: typeof PrivacyRoute
  RoofCostCalculatorRoute: typeof RoofCostCalculatorRoute
  RoofRepairCostRoute: typeof RoofRepairCostRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-disclosure': {
      id: '/affiliate-disclosure'
      path: '/affiliate-disclosure'
      fullPath: '/affiliate-disclosure'
      preLoaderRoute: typeof AffiliateDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flat-roof-cost': {
      id: '/flat-roof-cost'
      path: '/flat-roof-cost'
      fullPath: '/flat-roof-cost'
      preLoaderRoute: typeof FlatRoofCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-roof-cost': {
      id: '/new-roof-cost'
      path: '/new-roof-cost'
      fullPath: '/new-roof-cost'
      preLoaderRoute: typeof NewRoofCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roof-cost-calculator': {
      id: '/roof-cost-calculator'
      path: '/roof-cost-calculator'
      fullPath: '/roof-cost-calculator'
      preLoaderRoute: typeof RoofCostCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roof-repair-cost': {
      id: '/roof-repair-cost'
      path: '/roof-repair-cost'
      fullPath: '/roof-repair-cost'
      preLoaderRoute: typeof RoofRepairCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AffiliateDisclosureRoute: AffiliateDisclosureRoute,
  ContactRoute: ContactRoute,
  FlatRoofCostRoute: FlatRoofCostRoute,
  NewRoofCostRoute: NewRoofCostRoute,
  PrivacyRoute: PrivacyRoute,
  RoofCostCalculatorRoute: RoofCostCalculatorRoute,
  RoofRepairCostRoute: RoofRepairCostRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
